name : Bonjour tout le monde ! 
on : workflow-dispatch

env: 
  NAME: Max

jobs:
  bonjour:
    runs-on : ubuntu-lastest
    steps:
      - name: "Salut"
      if: ${{env.NAME != 'Max'}}
      run: echo "Salut toi ! Tu n'est max"
      if: ${{env.NAME == 'Max'}}
      run: echo "Salut $NAME"
      
