name: Bonjour tout le monde ! 
on: workflow_dispatch

env: 
  NAME: Max

jobs:
  bonjour:
    runs-on: ubuntu-latest
    steps:
      - name: "Salut"
        if: ${{env.NAME != 'Max'}}
        run: echo "Salut toi ! Tu n'est max"
      - name : "Salut Max"
        if: ${{env.NAME == 'Max'}}
        run: echo "Salut $NAME"
      
