name: Issue opened
on: 
    issues:
        types:
        - opened
jobs:
    issue_opened:
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v2
            - name: Issues opened
              run: 
                git checkout -b ${{ github.event.issue.number }}
                echo "issue créée"