name: Liste Fruits

on: workflow_dispatch

jobs:
  liste:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: true
      matrix:
        fruit: [pomme, banane, orange]
        noms: [Alexia, Bob, Raphael]
    steps:
      - name: Manger
        run: echo "${{ matrix.noms }} mange une ${{ matrix.fruit }} comme un gosse de 5 ans";